### ISSUE TITLE
[RMP] Transformers4Rec enhancements from recsys22 challenge 

### ISSUE THREAD

**Issue by sararb** [NVIDIA-Merlin/Transformers4Rec#412]
## Problem:
The support for session-based recommender models in T4rec was not updated since the code/examples were created for recsys21 and GTC-21. The recent competition recsys22 has increased the interest in the T4rec library, which provides an opportunity for us to test the library and point out any enhancements or limitations.  

## Goal:
The goal is to ensure T4rec has all the required components to develop a transformer-based solution for the recsys22 challenge. 

## Constraints:
What are the constraints that might impact the choice of solution?
This can also include non-constraints to clarify if something that would normally be a constraint is not a consideration.
Ideally this takes the form of a bulleted list.

### 22.07
- [x] Disable masking for inference/test time to leverage the whole input sequence. #436 
- [x] Ensuring that metrics names are prefixed as "eval_" instead of "eval/" to align with the HF integration code. #454 

### 22.07
- [x] Add the `PostFusionContext` block  #444 
- Note:  Based on previous T4R research experiments ([link to the script](https://github.com/NVIDIA-Merlin/competitions/blob/main/SIGIR_eCommerce_Challenge_2021/task1_session_based_rec/2-models/sigir_ecom_transformers/recsys_meta_model.py)), the `LatentCross` technique showed to be very effective. The script for Recsys22 includes the first implementation for this block. This must be released as part of the t4rec library. 
- [x] Add support for the prediction step to the Trainer class  #436 
- Note: This is a missing functionality in the current T4Rec library. This is required for the Recsys 22 challenge.  

- [x] Add support to sequential binary classification (i.e predicting a binary score for each position in the input sequence)
- Note: Add tasks related to the code to move from the private repo to the T4R library #434

**Comment by SaadAhmed433** [comment]
@sararb i am curious about the last point, I thought when we do prediction or inference from the model it always uses the entire sequence to predict the next item. Does this mean that currently at inference if the session has 10 items than the model will predict the next item based on the first 9 items? if so than if a session has just one item than would the model be still able to predict the next items?

Do I make sense? if the question isnt clear please let me know.

**Comment by sararb** [comment]
Hi @SaadAhmed433 !  

Currently, we apply the model with the flag `training=False` for the inference step (evaluation or prediction). In this scenario, the masking module masks the last item of the session (the 10th in your example) and uses it as the target. 
This is not what is expected for the inference step as the target is not part of the sequence and we need to feed all 10 interactions without any masking. For sessions with one item, the model will mask this item and the returned predictions will be random. 

I am currently working on a fix and hope it will be included in the library asap. In the meantime, I used a workaround for the recsys22 challenge where I am adding a fake item-id at the end of test sequences.

**Comment by lightsailpro** [comment]
@sararb I am current using docker image - "nvcr.io/nvidia/merlin/merlin-pytorch-training:22.03". Could you advise which merlin-pytorch docker image version will have the fix of "Disable masking for inference/test time to leverage the whole input sequence."? Is it in 22.07? I saw latest pulltag seems 22.05 though (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch-training). I am referring the following workaround you mentioned above:
"I am currently working on a fix and hope it will be included in the library asap. In the meantime, I used a workaround for the recsys22 challenge where I am adding a fake item-id at the end of test sequences."

Thanks a lot!

**Comment by sararb** [comment]
@lightsailpro, thank you for your interest in the library. The support of the prediction step in the Trainer class is under development and there is an open [PR](https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/436) proposing a possible fix. So it will likely be included in the upcoming release.

**Comment by viswa-nvidia** [comment]
@sararb , could you please add the problem, goal and constraints to the description. It may be available in other parts of this ticket. Could you help to summarize it at the top.  IF you are facing any difficulties / questions
 please let me know.

**Comment by viswa-nvidia** [comment]
### Future work
These two tickets should be moved out 
- [ ] https://github.com/NVIDIA-Merlin/Merlin/issues/274
- [ ] https://github.com/NVIDIA-Merlin/Merlin/issues/275
@sararb , please review this added scope. I am adding this from the Plan of record for 22.07. I understand that these are getting pushed out of 22.07 to future release. 

@sararb , How about session based recommendations integration in to T4R and MM ? Should that be tracked here or does it warrant a separate ticket ?

**Comment by viswa-nvidia** [comment]
Transferred pending tasks to this ticket and closing this one . https://github.com/NVIDIA-Merlin/Merlin/issues/477
